BOARD := t85db
#SKETCH := adc.ino
SKETCH := breathe.ino
#SKETCH := breathe2.ino
#SKETCH := timer.ino
#SKETCH := twilight3.ino
#SKETCH := useless.ino
#SKETCH := watchdog.ino
TERM_SPEED := 115200
include arduino-tiny.mk
