BOARD_NAME := Arduino Pro or Pro Mini
#BOARD := pro
BUILD_FCPU := 8000000L
BUILD_MCU := atmega328p
UPLOAD_SPEED := 57600
TERM_SPEED := 115200
#SKETCH := serialout.ino
SKETCH := serialin.ino
#SKETCH := adc.ino
#SKETCH := timer.ino
#SKETCH := watchdog.ino
#SKETCH := delay.ino
include arduino-avr.mk
