PROCESSOR_FAMILY := msp430
BOARD := lpmsp430g2553
SKETCH := serialout.ino
#SKETCH := serialin.ino
#SKETCH := temp.ino
#SKETCH := adc.ino
#SKETCH := useless.ino
#SKETCH := watchdog.ino

include energia.mk
