PROCESSOR_FAMILY := msp430
BOARD := MSP-EXP430G2553LP
#SKETCH := serialout.ino
#SKETCH := serialin.ino
#SKETCH := temp.ino
#SKETCH := adc.ino
#SKETCH := useless.ino
SKETCH := watchdog.ino

include energia.mk
