PROCESSOR_FAMILY := msp430
BOARD := lpmsp430fr5739
SKETCH := watchdog.ino
#SKETCH := temp.ino
#SKETCH := adc.ino
#SKETCH := serialin.ino
#SKETCH := serialout.ino
#SKETCH := pinchange.ino

include energia.mk
