PROCESSOR_FAMILY := msp430
BOARD := MSP-EXP430FR5739LP
#SKETCH := clock.ino
#SKETCH := accel.ino
SKETCH := useless.ino
#SKETCH := useless2.ino
#SKETCH := watchdog.ino
#SKETCH := temp.ino
#SKETCH := adc.ino
#SKETCH := serialin.ino
#SKETCH := serialout.ino
#SKETCH := pinchange.ino

include energia.mk
